---
abstract: 'Defines patterns for nic.at person handles'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Regexp-Common-AT-NICAT
provides:
  Regexp::Common::AT::NICAT:
    file: lib/Regexp/Common/AT/NICAT.pm
    version: 1.100860
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Regexp::Common: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Regexp-Common-AT-NICAT
  homepage: http://search.cpan.org/dist/Regexp-Common-AT-NICAT/
  repository: http://github.com/hanekomu/Regexp-Common-AT-NICAT
version: 1.100860
